version: '2'
services:
  parking:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/ppark'
    ports:
      - 3000:3000
    environment:
      - APP_ENV=dev
 
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    volumes:
      - './api:/api'
    ports:
      - 4000:4000
    depends_on:
      - parking

  database:
    build:
      context: ./database
      dockerfile: Dockerfile
    volumes:
      - './database:/var/lib/mysql'
    ports:
      - 3306:3306
    depends_on:
      - parking
